### ISSUE TITLE
Support Django 1.9 - 2.0 in a new release

### ISSUE THREAD

**Issue by jwhitlock** [mozilla/django-tidings#34]
[Kuma](https://github.com/mozilla/kuma) is updating to Django 1.11, and ``django-tidings`` needs an update to support it. Here's my plan for the next ``django-tidings`` release:

* [x] Drop support for Django 1.7 ~and Python 2.6~ *(was dropped in 1.2)*
* [x] Add a migration for Django 1.8's new column size in ``EmailField`` (see #26)
* [x] Drop ``jingo`` and convert the ``unsubscribe`` templates to Django-style templates (see #32)
* [x] Convert the test app to Celery 4.x, drop ``django-celery``, and add new task functions that can be serialized with JSON (see #33)
* [x] Update the test application to Django 1.8+ compatible settings (like moving ``TEMPLATE_DEBUG`` into ``TEMPLATES``, drop ``patterns``, etc.).
* [x] Update for new Django requirements, like explicit ``on_delete`` strategies
* [x] Add some compatibility functions for Django 2.0 changes, like ``User.is_anonymous`` as a property instead of a function.

I'm new to semantic versioning, so I'm not sure if that is a point release to 1.3 or a breaking 2.0 release. My inclination is 1.3. *Update: I'm convinced, it will be a 2.0 release*

**Comment by erikrose** [comment]
Dropping support for things is a major release in my book. It's wonderful to see the good work you're doing on this project!

**Comment by jwhitlock** [comment]
Thanks for the encouragement @erikrose, and I'm glad I can wipe the dust off a solid, well-tested, well-documented project.

The code is ready, now to package as release 2.0.
